import React from "react";
import { Compass, Layers, Database, Code, FileText, CalendarCheck, GitCommit } from "lucide-react";

export function EngineeringTakeawaysSection() {
  const takeaways = [
    {
      title: "System Design & Domain Decomposition",
      icon: <Layers className="w-4 h-4 text-sky-500" />,
      description:
        "Learned to model complex business domains into isolated modules before writing code. Defining domain boundaries early prevented cross-module contamination and created an extensible platform capable of accommodating future analytics and AI layers.",
    },
    {
      title: "Backend Architecture & Layered Separation",
      icon: <Code className="w-4 h-4 text-emerald-500" />,
      description:
        "Mastered the discipline of keeping routers completely clean of business logic and database queries. Encapsulating domain operations inside dedicated service classes made business rules easily testable, reusable, and independent of HTTP frameworks.",
    },
    {
      title: "Relational Database Modeling & Normalization",
      icon: <Database className="w-4 h-4 text-indigo-500" />,
      description:
        "Strengthened practical expertise in Third Normal Form (3NF) relational design. Solved complex associative relationships (M:N recipe ingredients with continuous quantities and 1:1 menu-recipe constraints) while ensuring foreign key cascade integrity.",
    },
    {
      title: "Contract-First API Design & Validation",
      icon: <FileText className="w-4 h-4 text-violet-500" />,
      description:
        "Adopted strict contract validation using Pydantic V2 and OpenAPI 3.1 specifications. Learned how well-defined DTOs and predictable HTTP status codes prevent integration friction when collaborating with future frontend engineers or external POS consumers.",
    },
    {
      title: "Deterministic Migration Workflows with Alembic",
      icon: <GitCommit className="w-4 h-4 text-amber-500" />,
      description:
        "Replaced manual schema modifications with version-controlled Alembic migrations. Practiced inspecting autogenerated revisions, enforcing bidirectional rollbacks, and keeping production schema states strictly reproducible in source control.",
    },
    {
      title: "Documentation-First Development",
      icon: <Compass className="w-4 h-4 text-rose-500" />,
      description:
        "Recognized that thorough technical documentation is not an afterthought but a core architectural deliverable. Writing comprehensive design documents and entity relationship definitions upfront accelerated backend implementation velocity.",
    },
    {
      title: "Planning Software Before Implementation",
      icon: <CalendarCheck className="w-4 h-4 text-teal-500" />,
      description:
        "Understood the value of phased milestone execution. Prioritizing backend infrastructure, database foundations, and core operational modules before attempting frontend or AI features prevented scope creep and yielded a resilient foundation.",
    },
  ];

  return (
    <section id="engineering-takeaways" aria-labelledby="takeaways-heading" className="scroll-mt-24 border-t border-zinc-200 dark:border-zinc-800 pt-12 space-y-8">
      <div>
        <div className="flex items-center gap-2 mb-3">
          <span className="font-mono text-xs font-semibold text-sky-600 dark:text-sky-400 uppercase tracking-widest">
            09 · PROFESSIONAL GROWTH &amp; SYSTEMS MATURITY
          </span>
        </div>
        <h2 id="takeaways-heading" className="text-2xl sm:text-3xl font-bold tracking-tight text-zinc-900 dark:text-zinc-50 font-sans mb-3">
          Engineering Takeaways
        </h2>
        <p className="text-zinc-600 dark:text-zinc-300 leading-relaxed max-w-3xl">
          Building RestaurantAI from inception to a verified modular foundation developed key capabilities in software architecture, database rigor, and production readiness:
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {takeaways.map((item, idx) => (
          <div
            key={idx}
            className="rounded-xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-950 p-5 flex items-start gap-3.5 shadow-xs"
          >
            <div className="p-2 rounded-lg bg-zinc-100 dark:bg-zinc-900 border border-zinc-200/80 dark:border-zinc-800/80 shrink-0">
              {item.icon}
            </div>
            <div className="space-y-1">
              <h3 className="font-semibold text-sm text-zinc-900 dark:text-zinc-100 font-sans">
                {item.title}
              </h3>
              <p className="text-xs text-zinc-500 dark:text-zinc-400 leading-relaxed">
                {item.description}
              </p>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}
