import React from "react";
import { CheckCircle2 } from "lucide-react";

export function EngineeringDecisionsSection() {
  const decisions = [
    {
      question: "Why FastAPI over Flask or Django?",
      summary: "High performance async ASGI runtime, native Pydantic typing, and automated OpenAPI documentation.",
      rationale: [
        "Flask requires significant boilerplate and third-party extensions for async support, schema validation, and OpenAPI generation, leading to inconsistent dependency versions across environments.",
        "Django is built around a monolithic MVC paradigm with heavy built-in assumptions (Django ORM, session cookies, templating engine) that create unnecessary overhead for a purely API-driven backend service.",
        "FastAPI provides native asynchronous ASGI throughput using Starlette, strict request/response data contracts via Pydantic V2, and built-in interactive OpenAPI 3.1 (/docs) with zero extra glue code.",
      ],
      tradeOff: "FastAPI is less 'batteries-included' than Django regarding admin interfaces, requiring explicit architecture design for migrations and service layers.",
    },
    {
      question: "Why SQLAlchemy 2.0 ORM?",
      summary: "Expressive relational modeling, explicit unit-of-work session pattern, and seamless Alembic integration.",
      rationale: [
        "Restaurant operations require intricate relational integrity: 1:1 constraints between Menu Items and Recipes, Many-to-Many junction records with quantities, and 1:N batch relationships.",
        "SQLAlchemy 2.0 provides declarative typing (<code className='font-mono text-xs'>Mapped[]</code>, <code className='font-mono text-xs'>mapped_column()</code>) that aligns with modern Python type checkers (Mypy).",
        "The explicit session lifecycle (<code className='font-mono text-xs'>session.add()</code>, <code className='font-mono text-xs'>session.commit()</code>) ensures ACID transactional boundaries across multi-table batch operations.",
      ],
      tradeOff: "Steeper learning curve and higher initial boilerplate compared to lightweight micro-ORMs like Peewee or raw SQL drivers.",
    },
    {
      question: "Why MySQL 8.0 with InnoDB?",
      summary: "Battle-tested relational ACID transactions, strict foreign key constraints, and mature enterprise tooling.",
      rationale: [
        "Inventory operations cannot tolerate eventual consistency or schema drift typical of NoSQL stores (e.g. MongoDB). Deducting batch stock requires row-level locking and strict transactional rollbacks on conflict.",
        "MySQL 8.0 offers robust indexing for composite queries (<code className='font-mono text-xs'>ingredient_id</code> + <code className='font-mono text-xs'>expiry_date</code>) essential for high-frequency FEFO queue resolution.",
        "Ubiquitous hosting support, predictable connection pooling behavior, and battle-proven durability in commercial enterprise environments.",
      ],
      tradeOff: "Schema migrations require planned DDL execution and indexing considerations, which are mitigated via Alembic.",
    },
    {
      question: "Why Alembic for Database Migrations?",
      summary: "Deterministic, code-reviewed schema versioning strictly coupled with Git source control.",
      rationale: [
        "Manual <code className='font-mono text-xs'>ALTER TABLE</code> execution in production environments is prone to human error, drift between development and production, and unrecoverable downtime.",
        "Alembic autogenerates migration scripts directly by inspecting SQLAlchemy declarative metadata against the live database catalog.",
        "Supports bidirectional migrations (upgrade and downgrade scripts), enabling safe continuous delivery and rollback capabilities.",
      ],
      tradeOff: "Autogenerated migrations must be manually inspected to ensure correct column type conversions and foreign key naming.",
    },
    {
      question: "Why Layered Architecture (Routers → Services → ORM)?",
      summary: "Strict separation of concerns preventing HTTP transport details from polluting core restaurant business rules.",
      rationale: [
        "Routers are purely responsible for HTTP parsing, status code selection, and Pydantic DTO serialization.",
        "Domain Services house pure Python business algorithms (e.g. availability formulas, batch auto-numbering, recipe scaling) without dependencies on FastAPI request objects.",
        "Data Access Models focus strictly on table mappings and foreign keys. This allows swapping databases or adding background workers without rewriting business logic.",
      ],
      tradeOff: "Requires creating distinct DTO schemas and mapping logic between ORM entities and API representations, adding modest file overhead.",
    },
    {
      question: "Why Modular Monolith instead of Microservices?",
      summary: "Avoids premature distributed system complexity while maintaining clean domain boundaries for future decomposition.",
      rationale: [
        "Microservices introduce distributed tracing, network latency, eventual consistency, inter-service authentication, and complex deployment topologies that slow velocity for early-stage systems.",
        "A modular monolith provides domain encapsulation within a single deployable artifact and single shared transactional database.",
        "Because modules (Ingredients, Menus, Recipes, Batches) have zero circular dependencies, any module can be extracted into an independent microservice in the future if specific scaling bottlenecks emerge.",
      ],
      tradeOff: "Shared database transactions could theoretically be abused if developers bypass service boundaries (prevented by strict code organization).",
    },
    {
      question: "Why RESTful APIs?",
      summary: "Predictable resource-oriented contracts, standard HTTP semantics, and universal client compatibility.",
      rationale: [
        "Restaurant operations map naturally to noun-based resources (<code className='font-mono text-xs'>/ingredients</code>, <code className='font-mono text-xs'>/recipes</code>, <code className='font-mono text-xs'>/inventory/batches</code>).",
        "Standard HTTP verbs (GET, POST, PUT, DELETE) and status codes (200 OK, 201 Created, 404 Not Found, 409 Conflict, 422 Unprocessable) provide clear operational semantics.",
        "Simplifies future frontend integration with React, as well as potential hardware integrations with POS terminals and Kitchen Display Systems.",
      ],
      tradeOff: "REST may lead to over-fetching or under-fetching if consumer requirements diverge significantly, which can be mitigated with filtered query parameters.",
    },
  ];

  return (
    <section id="engineering-decisions" aria-labelledby="decisions-heading" className="scroll-mt-24 border-t border-zinc-200 dark:border-zinc-800 pt-12 space-y-10">
      <div>
        <div className="flex items-center gap-2 mb-3">
          <span className="font-mono text-xs font-semibold text-sky-600 dark:text-sky-400 uppercase tracking-widest">
            07 · ARCHITECTURAL TRADE-OFFS &amp; DECISIONS
          </span>
        </div>
        <h2 id="decisions-heading" className="text-2xl sm:text-3xl font-bold tracking-tight text-zinc-900 dark:text-zinc-50 font-sans mb-3">
          Why These Technologies &amp; Patterns?
        </h2>
        <p className="text-zinc-600 dark:text-zinc-300 leading-relaxed max-w-3xl">
          Engineering maturity is measured by the ability to justify architectural trade-offs. Rather than selecting popular tools blindly, each technology and architectural pattern was chosen to solve specific operational constraints:
        </p>
      </div>

      <div className="grid grid-cols-1 gap-6">
        {decisions.map((d, idx) => (
          <div
            key={idx}
            className="rounded-xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-950 p-5 sm:p-6 transition-colors shadow-xs"
          >
            <div className="flex items-start justify-between gap-4 mb-2">
              <h3 className="font-bold text-base sm:text-lg text-zinc-900 dark:text-zinc-100 font-sans flex items-center gap-2">
                <span className="font-mono text-xs text-sky-600 dark:text-sky-400 font-semibold px-2 py-0.5 rounded bg-sky-50 dark:bg-sky-950/50 border border-sky-200 dark:border-sky-800/60 shrink-0">
                  DEC-{idx + 1 < 10 ? `0${idx + 1}` : idx + 1}
                </span>
                {d.question}
              </h3>
            </div>

            <p className="text-xs sm:text-sm font-medium text-sky-700 dark:text-sky-300 mb-4 pl-1">
              Core Rationale: {d.summary}
            </p>

            <div className="space-y-2.5 mb-4 pl-1">
              {d.rationale.map((point, pIdx) => (
                <div key={pIdx} className="flex items-start gap-2.5 text-xs text-zinc-600 dark:text-zinc-400 leading-relaxed">
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500 shrink-0 mt-0.5" />
                  <span dangerouslySetInnerHTML={{ __html: point }} />
                </div>
              ))}
            </div>

            <div className="pt-3 border-t border-zinc-100 dark:border-zinc-800/80 flex items-start gap-2 text-xs text-zinc-500 dark:text-zinc-400 pl-1">
              <span className="font-mono text-[10px] uppercase tracking-wider text-amber-600 dark:text-amber-400 font-semibold shrink-0 mt-0.5">
                Trade-off:
              </span>
              <span>{d.tradeOff}</span>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}
